insert into NHACUNGCAP(MANCC, TENNHACC, DIACHI, SODIENTHOAI) values ("NCC01","PTM","Dist 9. TPHCM","0929283721")

insert into DIENTHOAI(MADT,TENDT,NAMSANXUAT,CAUHINH,MANCC,HINHANH) values("DT01","NOKIA",2020,"ABC","NCC01","image1.png");
insert into DIENTHOAI(MADT,TENDT,NAMSANXUAT,CAUHINH,MANCC,HINHANH) values("DT02","LUMIA",2019,"ABC","NCC01","image2.png");
insert into DIENTHOAI(MADT,TENDT,NAMSANXUAT,CAUHINH,MANCC,HINHANH) values("DT03","HELL",2018,"ABC","NCC01","image3.png");
insert into DIENTHOAI(MADT,TENDT,NAMSANXUAT,CAUHINH,MANCC,HINHANH) values("DT04","IPHONE",2021,"ABC","NCC01","image4.png");
insert into DIENTHOAI(MADT,TENDT,NAMSANXUAT,CAUHINH,MANCC,HINHANH) values("DT05","NUBIA",2022,"ABC","NCC01","image5.png");